# This is a basic workflow to help you get started with Actions

name: Hexo Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
        # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout source
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      - name: Import lint-md
        run: |
          npm update npm
          npm i -g @lint-md/cli
          npm i -g @lint-md/cli
        
      - name: Fix format of markdown sources
        run: |
          find ./source/ -name "*.md" | echo "mds:" 
          find ./source/ -name "*.md" | lint-md --fix 
      
      - name: Commit the fix
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Fix format of markdown sources."
          git push

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "i@icys.top"
          git config --global user.name "icy-blue"
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo deploy
