# This is a basic workflow to help you get started with Actions

name: Lint and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-format:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      - name: Import lint-md
        run: |
          npm update npm
          npm i -g @lint-md/cli
          npm i -g @lint-md/core
        
      - name: Fix format of markdown sources
        shell: bash
        run: |
          find ./source/ -name "*.md" | xargs lint-md --fix 
          
      - name: Commit the fix
        run: |
          git config --global user.email "i@icys.top"
          git config --global user.name "icy-blue"
          git add --all
          git commit -m "Fix format of markdown sources."
          git push

  deploy-github:
    needs: lint-format
    runs-on: ubuntu-latest

    steps:
        # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout source
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install
        
      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "i@icys.top"
          git config --global user.name "icy-blue"

      - name: Deploy
        run: |
          cat >> _config.yml <<EOF

          # 自动部署配置
          deploy:
            type: git
            repo: git@github.com:icy-blue/icy-blue.github.io.git
            branch: hexo

          EOF
          hexo clean
          hexo deploy
 
  deploy-gitee:
    needs: lint-format
    runs-on: ubuntu-latest

    steps:
        # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout source
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install
        
      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          git config --global user.email "i@icys.top"
          git config --global user.name "icy-blue"

      - name: Deploy
        run: |
          cat >> _config.yml <<EOF

          # 自动部署配置
          deploy:
            type: git
            repo: git@gitee.com:icy-blue/icy-blue.gitee.io.git
            branch: hexo

          EOF
          hexo clean
          hexo deploy
          hexo deploy
