name: Lint and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint-format:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Import lint-md
        run: |
          npm update npm
          npm i -g @lint-md/cli
          npm i -g @lint-md/core
        
      - name: Fix format of markdown sources
        shell: bash
        run: |
          find ./source/ -name "*.md" | xargs lint-md --fix
          
      - name: Commit the fix
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add --all
          git commit -m "Fix format of markdown sources."
          git push

  deploy-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy COS
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.COS_DEPLOY_KEYS }}
        run: |
          pip install -U argparse cos-python-sdk-v5
          python ./.github/workflows/upload.py $ACTION_DEPLOY_KEY >> "$GITHUB_OUTPUT"
          
      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.IMAGE_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git pull
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Upload Images
        run: |
          cd source/images/
          git config --global init.defaultBranch main
          git init
          git remote add origin git@github.com:icy-blue/images.git
          git add .
          git commit -m "Add images."
          git push --force --set-upstream origin main

  deploy-blog-github:
    needs: [ deploy-images, lint-format ]
    runs-on: ubuntu-latest

    steps:
        # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install
        
      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          rm ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git pull
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          rm source/images/ -rf

      - name: Deploy
        run: |
          cat >> _config.yml <<EOF

          # 自动部署配置
          deploy:
            type: git
            repo: git@github.com:icy-blue/icy-blue.github.io.git
            branch: hexo

          EOF
          hexo clean
          hexo deploy

  deploy-blog-gitee:
    needs: [ deploy-images, lint-format, deploy-blog-github ]
    runs-on: ubuntu-latest

    steps:
        # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install hexo-deployer-git --save
          npm install
        
      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          rm ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git pull
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          rm source/images/ -rf

      - name: Deploy
        run: |
          cat >> _config.yml <<EOF

          # 自动部署配置
          deploy:
            type: git
            repo: git@gitee.com:icy-blue/blog-deploy.git
            branch: main

          EOF
          hexo clean
          hexo deploy
